- name: Install postfix
  apt: pkg=postfix state=latest
- name: Install postfix-mysql
  apt: pkg=postfix-mysql state=latest
- name: Install postgrey
  apt: pkg=postgrey state=latest
- name: Install python-mysqldb
  apt: pkg=python-mysqldb state=latest
- name: Install sasl modules
  apt: pkg=libsasl2-modules state=latest
- name: "/etc/postfix/main.cf: smtpd_tls_cert_file=/etc/ssl/certs/this-machine.pem"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*smtpd_tls_cert_file\s*=" line="smtpd_tls_cert_file=/etc/ssl/certs/this-machine.pem"
- name: "/etc/postfix/main.cf: smtpd_tls_key_file=/etc/ssl/private/this-machine.pem"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*smtpd_tls_key_file\s*=" line="smtpd_tls_key_file=/etc/ssl/private/this-machine.pem"
- name: "/etc/postfix/main.cf: smtpd_use_tls=yes"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*smtpd_use_tls\s*=" line="smtpd_use_tls=yes"
- name: "/etc/postfix/main.cf: smtpd_tls_auth_only = yes"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*smtpd_tls_auth_only\s*=" line="smtpd_tls_auth_only = yes"
- name: "/etc/postfix/main.cf: smtp_tls_security_level = may"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*smtp_tls_security_level\s*=" line="smtp_tls_security_level = may"
- name: "/etc/postfix/main.cf: smtp_tls_loglevel = 2"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*smtp_tls_loglevel\s*=" line="smtp_tls_loglevel = 2"
- name: "/etc/postfix/main.cf: smtpd_tls_received_header = yes"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*smtpd_tls_received_header\s*=" line="smtpd_tls_received_header = yes"
- name: "/etc/postfix/main.cf: smtp_tls_mandatory_protocols = !SSLv2,!SSLv3,!TLSv1,!TLSv1.1"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*smtp_tls_mandatory_protocols\s*=" line="smtp_tls_mandatory_protocols = !SSLv2,!SSLv3,!TLSv1,!TLSv1.1"
- name: "/etc/postfix/main.cf: smtp_tls_protocols = !SSLv2,!SSLv3,!TLSv1,!TLSv1.1"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*smtp_tls_protocols\s*=" line="smtp_tls_protocols = !SSLv2,!SSLv3,!TLSv1,!TLSv1.1"
- name: "/etc/postfix/main.cf: smtpd_tls_mandatory_protocols = !SSLv2,!SSLv3,!TLSv1,!TLSv1.1"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*smtpd_tls_mandatory_protocols\s*=" line="smtpd_tls_mandatory_protocols = !SSLv2,!SSLv3,!TLSv1,!TLSv1.1"
- name: "/etc/postfix/main.cf: smtpd_tls_protocols = !SSLv2,!SSLv3,!TLSv1,!TLSv1.1"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*smtpd_tls_protocols\s*=" line="smtpd_tls_protocols = !SSLv2,!SSLv3,!TLSv1,!TLSv1.1"
- name: "/etc/postfix/main.cf: smtpd_tls_mandatory_ciphers = medium"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*smtpd_tls_mandatory_ciphers\s*=" line="smtpd_tls_mandatory_ciphers = medium"
- name: "/etc/postfix/main.cf: smtpd_sasl_type = dovecot"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*smtpd_sasl_type\s*=" line="smtpd_sasl_type = dovecot"
- name: "/etc/postfix/main.cf: smtpd_sasl_path = private/auth"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*smtpd_sasl_path\s*=" line="smtpd_sasl_path = private/auth"
- name: "/etc/postfix/main.cf: smtpd_recipient_restrictions = permit_sasl_authenticated, permit_mynetworks, reject_unauth_pipelining, reject_unauth_destination, reject_invalid_hostname, reject_non_fqdn_hostname, reject_non_fqdn_recipient, reject_unknown_recipient_domain"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*smtpd_recipient_restrictions\s*=" line="smtpd_recipient_restrictions = permit_sasl_authenticated, permit_mynetworks, reject_unauth_pipelining, reject_unauth_destination, reject_invalid_hostname, reject_non_fqdn_hostname, reject_non_fqdn_recipient, reject_unknown_recipient_domain"
- name: "/etc/postfix/main.cf: mydestination = localhost"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*mydestination\s*=" line="mydestination = localhost"
- name: "/etc/postfix/main.cf: virtual_transport = lmtp:unix:private/dovecot-lmtp"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*virtual_transport\s*=" line="virtual_transport = lmtp:unix:private/dovecot-lmtp"
- name: "/etc/postfix/main.cf: virtual_mailbox_domains = mysql:/etc/postfix/mysql-virtual-mailbox-domains.cf"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*virtual_mailbox_domains\s*" line="virtual_mailbox_domains = mysql:/etc/postfix/mysql-virtual-mailbox-domains.cf"
- name: "/etc/postfix/main.cf: virtual_mailbox_maps = mysql:/etc/postfix/mysql-virtual-mailbox-maps.cf"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*virtual_mailbox_maps\s*=" line="virtual_mailbox_maps = mysql:/etc/postfix/mysql-virtual-mailbox-maps.cf"
- name: "/etc/postfix/main.cf: virtual_alias_maps = mysql:/etc/postfix/mysql-virtual-alias-maps.cf"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*virtual_alias_maps\s*=" line="virtual_alias_maps = mysql:/etc/postfix/mysql-virtual-alias-maps.cf"
- name: "/etc/postfix/main.cf: message_size_limit = 2048000000"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*message_size_limit\s=" line="message_size_limit = 2048000000"
- name: "/etc/postfix/main.cf: smtpd_tls_security_level = may"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*smtpd_tls_security_level\s=" line="smtpd_tls_security_level = may"
- name: "/etc/postfix/main.cf: smtpd_tls_dh1024_param_file = /etc/ssl/dhparams.pem"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*smtpd_tls_dh1024_param_file\s=" line="smtpd_tls_dh1024_param_file = /etc/ssl/dhparams.pem"
- name: "/etc/postfix/main.cf: tls_medium_cipherlist = AES128+EECDH:AES128+EDH"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*tls_medium_cipherlist\s=" line="tls_medium_cipherlist = AES128+EECDH:AES128+EDH"
- name: "/etc/postfix/main.cf: local_recipient_maps = $virtual_mailbox_maps"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*local_recipient_maps\s=" line="local_recipient_maps = $virtual_mailbox_maps"
- name: "/etc/postfix/main.cf: smtpd_helo_required = yes"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*smtpd_helo_required\s=" line="smtpd_helo_required = yes"
- name: "/etc/postfix/main.cf: smtpd_helo_restrictions = permit_mynetworks, reject_invalid_hostname"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*smtpd_helo_restrictions\s=" line="smtpd_helo_restrictions = permit_mynetworks, reject_invalid_hostname"
- name: "/etc/postfix/main.cf: smtpd_sender_restrictions = reject_unknown_address"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*smtpd_sender_restrictions\s=" line="smtpd_sender_restrictions = reject_unknown_address"
- name: "/etc/postfix/main.cf: disable_vrfy_command = yes"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*disable_vrfy_command\s=" line="disable_vrfy_command = yes"
- name: "/etc/postfix/main.cf: strict_rfc821_envelopes = yes"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*strict_rfc821_envelopes\s=" line="strict_rfc821_envelopes = yes"
- name: "/etc/postfix/main.cf: postscreen_access_list = permit_mynetworks"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*postscreen_access_list\s=" line="postscreen_access_list = permit_mynetworks"
- name: "/etc/postfix/main.cf: postscreen_dnsbl_sites = sbl-xbl.spamhaus.org*2 cbl.abuseat.org*2 bl.spamcop.net*2 dnsbl.sorbs.net*1 spam.spamrats.com*2"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*postscreen_dnsbl_sites\s=" line="postscreen_dnsbl_sites = sbl-xbl.spamhaus.org*2 cbl.abuseat.org*2 bl.spamcop.net*2 dnsbl.sorbs.net*1 spam.spamrats.com*2"
- name: "/etc/postfix/main.cf: postscreen_dnsbl_threshold = 3"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*postscreen_dnsbl_threshold\s=" line="postscreen_dnsbl_threshold = 3"
- name: "/etc/postfix/main.cf: postscreen_dnsbl_action = enforce"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*postscreen_dnsbl_action\s=" line="postscreen_dnsbl_action = enforce"
- name: "/etc/postfix/main.cf: postscreen_greet_action = enforce"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*postscreen_greet_action\s=" line="postscreen_greet_action = enforce"
- name: "/etc/postfix/main.cf: smtp_use_tls = yes"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*smtp_use_tls\s=" line="smtp_use_tls = yes"
- name: "/etc/postfix/main.cf: smtp_sasl_auth_enable = yes"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*smtp_sasl_auth_enable\s=" line="smtp_sasl_auth_enable = yes"
- name: "/etc/postfix/main.cf: smtp_sasl_security_options = noanonymous"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*smtp_sasl_security_options\s=" line="smtp_sasl_security_options = noanonymous"
- name: "/etc/postfix/main.cf: smtp_always_send_ehlo = yes"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*smtp_always_send_ehlo\s=" line="smtp_always_send_ehlo = yes"
- name: "/etc/postfix/main.cf: smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*smtp_tls_CAfile\s=" line="smtp_tls_CAfile = /etc/ssl/certs/ca-certificates.crt"

- name: "/etc/postfix/main.cf: smtpd_sasl_auth_enable = yes"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*smtpd_sasl_auth_enable\s*=" line="smtpd_sasl_auth_enable = yes"
  when: postfix.relay_host
- name: "/etc/postfix/main.cf: smtp_sasl_password_maps = hash:/etc/postfix/relay_password"
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*smtp_sasl_password_maps\s=" line="smtp_sasl_password_maps = hash:/etc/postfix/relay_password"
  when: postfix.relay_host
- name: "/etc/postfix/main.cf: relayhost = ..."
  lineinfile: dest=/etc/postfix/main.cf regexp="^#?\s*relayhost\s=" line="relayhost = {{ postfix.relay_host }}"
  when: postfix.relay_host
- name: "/etc/postfix/relay_password: create"
  file: path=/etc/postfix/relay_password mode=0600 state=touch
  when: postfix.relay_host
- name: "/etc/postfix/relay_password: credentials"
  lineinfile: dest=/etc/postfix/relay_password line="{{ postfix.relay_host }} {{ postfix.relay_username }}:{{ postfix.relay_password }}"
  when: postfix.relay_host
- name: "postmap /etc/postfix/relay_password"
  shell: "/usr/sbin/postmap /etc/postfix/relay_password"
  when: postfix.relay_host

- name: "/etc/postfix/master.cf: enable smtps"
  lineinfile: dest=/etc/postfix/master.cf line="smtps     inet  n       -       -       -       -       smtpd\n  -o syslog_name=postfix/smtps\n  -o smtpd_tls_wrappermode=yes\n  -o smtpd_sasl_auth_enable=yes\n  -o smtpd_reject_unlisted_recipient=no\n  -o smtpd_client_restrictions=$mua_client_restrictions\n  -o smtpd_helo_restrictions=$mua_helo_restrictions\n  -o smtpd_sender_restrictions=$mua_sender_restrictions\n  -o smtpd_recipient_restrictions=\n  -o smtpd_relay_restrictions=permit_sasl_authenticated,reject\n  -o milter_macro_daemon_name=ORIGINATING"
- name: "comment smtp for postscreen"
  lineinfile: dest=/etc/postfix/master.cf regexp="^#?\s*smtp.*smtpd\s*$" line="#smtp      inet  n       -       -       -       -       smtpd"
- name: "uncomment postscreen (smtp)"
  lineinfile: dest=/etc/postfix/master.cf regexp="^#?\s*smtp.*postscreen\s*$" line="smtp      inet  n       -       -       -       1       postscreen"
- name: "uncomment postscreen (smtpd)"
  lineinfile: dest=/etc/postfix/master.cf regexp="^#?\s*smtpd.*smtpd\s*$" line="smtpd     pass  -       -       -       -       -       smtpd"
- name: "uncomment postscreen (dnsblog)"
  lineinfile: dest=/etc/postfix/master.cf regexp="^#?\s*dnsblog.*dnsblog\s*$" line="dnsblog   unix  -       -       -       -       0       dnsblog"
- name: "uncomment postscreen (tlsproxy)"
  lineinfile: dest=/etc/postfix/master.cf regexp="^#?\s*tlsproxy.*tlsproxy\s*$" line="tlsproxy  unix  -       -       -       -       0       tlsproxy"
- name: "/etc/postfix/mysql-virtual-mailbox-domains.cf"
  template: src=roles/postfix/templates/mysql-virtual-mailbox-domains.cf.j2 dest=/etc/postfix/mysql-virtual-mailbox-domains.cf
- name: "/etc/postfix/mysql-virtual-mailbox-maps.cf"
  template: src=roles/postfix/templates/mysql-virtual-mailbox-maps.cf.j2 dest=/etc/postfix/mysql-virtual-mailbox-maps.cf
- name: "/etc/postfix/mysql-virtual-alias-maps.cf"
  template: src=roles/postfix/templates/mysql-virtual-alias-maps.cf.j2 dest=/etc/postfix/mysql-virtual-alias-maps.cf
- name: Restart postfix
  service: state=restarted name=postfix
